# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(default=b'', max_length=30)),
                ('menu', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
