# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyoammeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
